#!/bin/sh
#------------------------------------------------------------------------------
# Copyright (C) 2004 The ExTeX Group
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#------------------------------------------------------------------------------
# THIS FILE SHOULD BE EXECUTABLE.
#------------------------------------------------------------------------------

verbose=0
if [ "$1" = "-v" ] ; then
    shift
    verbose=1
fi
if [ "$1" = "-q" ] ; then
    shift
    verbose=0
fi

if [ $verbose = 1 ] ; then
    echo
    echo "ExTeX Build System"
    echo "------------------"
    echo
fi

if [ "$JAVA_HOME" = "" ] ; then
    echo "ERROR: JAVA_HOME not found in your environment."
    echo
    echo "Please, set the JAVA_HOME variable in your environment to match the"
    echo "location of the Java Virtual Machine you want to use."
    exit 1
fi

# OS specific support.  $var _must_ be set to either true or false.
cygwin=false;
case "`uname`" in
    CYGWIN*) cygwin=true ;;
esac

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin ; then
    [ -n "$JAVA_HOME" ] &&
        JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
fi

LIBDIR=lib

LOCALCLASSPATH=.
LOCALCLASSPATH=$JAVA_HOME/lib/tools.jar
LOCALCLASSPATH=$LOCALCLASSPATH:$JAVA_HOME/lib/classes.zip

# jar-Dateien
#for i in $LIBDIR/*.jar ; do
#    LOCALCLASSPATH=$LOCALCLASSPATH:$i
#done

# jar-Dateien
for i in lib.develop/*.jar ; do
    LOCALCLASSPATH=$LOCALCLASSPATH:$i
done

# export $LOCALCLASSPATH

# antRun must be executable (can't do this in build.xml because Ant uses antRun
# to do the chmod)
chmod +rx util/antRun

ANT_HOME=$LIBDIR

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
    LOCALCLASSPATH=`cygpath --path --windows "$LOCALCLASSPATH"`
fi

if [ $verbose = 1 ] ; then
    echo
    echo $JAVA_HOME
    echo Building with classpath $LOCALCLASSPATH
    echo Starting Ant...
    echo
fi

$JAVA_HOME/bin/java -Dant.home=$ANT_HOME -classpath "$LOCALCLASSPATH" org.apache.tools.ant.Main $*
