#!/bin/sh
#------------------------------------------------------------------------------
# This is the start script for ExTeX
#------------------------------------------------------------------------------
# Copyright (C) 2004-2006 The ExTeX Group
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#------------------------------------------------------------------------------

if [ "$JAVA_HOME" = "" ] ; then
  echo "ERROR: JAVA_HOME not found in your environment."
  echo
  echo "Please, set the JAVA_HOME variable in your environment to match the"
  echo "location of the Java Virtual Machine you want to use."
  exit 1
fi

EXTEX_HOME=`dirname $0`
LIBDIR="$EXTEX_HOME/lib"

# OS specific support.
case "`uname`" in
  CYGWIN*)
    # For Cygwin, ensure paths are in UNIX format before anything is touched
    [ -n "$JAVA_HOME" ] &&
        JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
    sep=';'
    LOCALCLASSPATH=.$sep$EXTEX_HOME/config$sep$EXTEX_HOME/target/classes
    for i in $LIBDIR/*.jar ; do
      LOCALCLASSPATH=$LOCALCLASSPATH$sep`cygpath --unix "$i"`
    done
    for i in $EXTEX_HOME/target/lib/*.jar ; do
      LOCALCLASSPATH=$LOCALCLASSPATH$sep`cygpath --unix "$i"`
    done
    ;;
  *)
    sep=':'
    LOCALCLASSPATH=.$sep$EXTEX_HOME/config$sep$EXTEX_HOME/target/classes
    for i in $LIBDIR/*.jar ; do
      LOCALCLASSPATH=$LOCALCLASSPATH$sep$i
    done
    for i in $EXTEX_HOME/target/lib/*.jar ; do
      LOCALCLASSPATH=$LOCALCLASSPATH$sep$i
    done
    ;;
esac

exec java $EXTEX_JAVA_OPTS -classpath "$LOCALCLASSPATH" \
    de.dante.extex.main.TeX -progname=`basename $0` $*

#