#!/bin/sh

if [ -z $1 ]; then
	echo -e "\nPlease specify a target directory on the command line."
	echo -e "\"./install-extex /target/dir\"\n\n"
	exit 1
fi

targetdirectory=$1

if [ ! -d $1 ]; then
	echo -e "\nThe directory \"$targetdirectory\" does not exist."
	echo -e "Installation aborted.\n\n"
	exit 1
fi

cp -a build.xml $targetdirectory
cp -a build $targetdirectory
cp -a extex $targetdirectory
cp -a lib/ $targetdirectory
cp -a lib.develop/ $targetdirectory
cp -a font/ $targetdirectory
cp -a util/ $targetdirectory
cp -a testdata/ $targetdirectory
cp -a src/ $targetdirectory

cd $targetdirectory

./build jar

cd tmp/classes

cp -a config/ ../../
cp -a de/ ../../

cd ../../

echo -e "\n\nExTeX is now installed in $targetdirectory"
echo -e "To invoke ExTeX use \"./extex ...\" in this directory.\n\n"