#******************************************************************************
#* $Id: Makefile,v 1.3 2003/12/30 08:35:59 gene Exp $
#******************************************************************************
#* Author: Gerd Neugebauer
#*=============================================================================

OPT =
BASEDIR = ../..
CSS = ${BASEDIR}/src/javadoc/stylesheet.css
OUTFILE = doc.html

all:
	@perl docmaker $(OPT) -o $(OUTFILE) -css ${CSS} ${BASEDIR}/src/java

clean:

#
