#!/bin/sh
#------------------------------------------------------------------------------
# This is the start script for ExTeX
#------------------------------------------------------------------------------
# Copyright (C) 2004 The ExTeX Group
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
#------------------------------------------------------------------------------

EXTEX_HOME="$INSTALL_PATH"
JAVA_DIR="$JAVA_HOME"

case "`uname`" in
  CYGWIN*)    sep=';'    ;;
  *)          sep=':'    ;;
esac

CP=.
for i in $EXTEX_HOME/lib/*.jar ; do
    CP=$CP$sep$i
done
CP=$CP$sep$EXTEX_HOME/

exec $JAVA_DIR/bin/java -classpath "$CP" de.dante.extex.ExTeX $*
  
#